/*
 *      DO NOT EDIT THIS FILE
 *
 *      Copy this file when you create
 *      a new quadrature and search for
 *      the word "dummy" and replace it
 *      with the actual content.
 *
 *
 */

#include "qdummy.h"

QDummy::QDummy( unsigned order ) : Quadrature( order ) {
    SetName( ComputeName() );
    SetNq( ComputeNq() );
    SetPoints( ComputePoints() );
    SetWeights( ComputeWeights() );
    SetConnectivity( ComputeConnectivity() );
}

std::string QDummy::ComputeName() {
    std::string name = "";
    // @TODO: DUMMYCOMPUTATION
    return name;
}

unsigned QDummy::ComputeNq() {
    unsigned nq = 0;
    // @TODO: DUMMYCOMPUTATION
    return nq;
};

VectorVector QDummy::ComputePoints() {
    unsigned nq = GetNq();
    VectorVector points( nq );
    // @TODO: DUMMYCOMPUTATION
    return points;
};

Vector QDummy::ComputeWeights() {
    unsigned nq = GetNq();
    Vector weights( nq, 4.0 * M_PI / nq );
    // @TODO: DUMMYCOMPUTATION
    return weights;
};

VectorVectorU QDummy::ComputeConnectivity() {
    VectorVectorU connectivity;
    // @TODO: DUMMYCOMPUTATION
    return connectivity;
};
