add_test( SN_SOLVER /home/jonas/Projects/rtsn/build-code-Desktop-Release/unit_tests SN_SOLVER)
set_tests_properties( SN_SOLVER PROPERTIES WORKING_DIRECTORY /home/jonas/Projects/rtsn/build-code-Desktop-Release)
add_test( PN_SOLVER /home/jonas/Projects/rtsn/build-code-Desktop-Release/unit_tests PN_SOLVER)
set_tests_properties( PN_SOLVER PROPERTIES WORKING_DIRECTORY /home/jonas/Projects/rtsn/build-code-Desktop-Release)
add_test( MN_SOLVER /home/jonas/Projects/rtsn/build-code-Desktop-Release/unit_tests MN_SOLVER)
set_tests_properties( MN_SOLVER PROPERTIES WORKING_DIRECTORY /home/jonas/Projects/rtsn/build-code-Desktop-Release)
add_test( screen_output /home/jonas/Projects/rtsn/build-code-Desktop-Release/unit_tests screen_output)
set_tests_properties( screen_output PROPERTIES WORKING_DIRECTORY /home/jonas/Projects/rtsn/build-code-Desktop-Release)
add_test( [==[Read in Config Template]==] /home/jonas/Projects/rtsn/build-code-Desktop-Release/unit_tests [==[Read in Config Template]==])
set_tests_properties( [==[Read in Config Template]==] PROPERTIES WORKING_DIRECTORY /home/jonas/Projects/rtsn/build-code-Desktop-Release)
add_test( [==[test the spherical harmonics basis computation]==] /home/jonas/Projects/rtsn/build-code-Desktop-Release/unit_tests [==[test the spherical harmonics basis computation]==])
set_tests_properties( [==[test the spherical harmonics basis computation]==] PROPERTIES WORKING_DIRECTORY /home/jonas/Projects/rtsn/build-code-Desktop-Release)
add_test( [==[convert image data to grayscale matrix]==] /home/jonas/Projects/rtsn/build-code-Desktop-Release/unit_tests [==[convert image data to grayscale matrix]==])
set_tests_properties( [==[convert image data to grayscale matrix]==] PROPERTIES WORKING_DIRECTORY /home/jonas/Projects/rtsn/build-code-Desktop-Release)
add_test( [==[interpolation tests]==] /home/jonas/Projects/rtsn/build-code-Desktop-Release/unit_tests [==[interpolation tests]==])
set_tests_properties( [==[interpolation tests]==] PROPERTIES WORKING_DIRECTORY /home/jonas/Projects/rtsn/build-code-Desktop-Release)
add_test( [==[test all scattering kernels]==] /home/jonas/Projects/rtsn/build-code-Desktop-Release/unit_tests [==[test all scattering kernels]==])
set_tests_properties( [==[test all scattering kernels]==] PROPERTIES WORKING_DIRECTORY /home/jonas/Projects/rtsn/build-code-Desktop-Release)
add_test( [==[unit mesh tests]==] /home/jonas/Projects/rtsn/build-code-Desktop-Release/unit_tests [==[unit mesh tests]==])
set_tests_properties( [==[unit mesh tests]==] PROPERTIES WORKING_DIRECTORY /home/jonas/Projects/rtsn/build-code-Desktop-Release)
add_test( [==[unit numericalflux tests]==] /home/jonas/Projects/rtsn/build-code-Desktop-Release/unit_tests [==[unit numericalflux tests]==])
set_tests_properties( [==[unit numericalflux tests]==] PROPERTIES WORKING_DIRECTORY /home/jonas/Projects/rtsn/build-code-Desktop-Release)
add_test( [==[Test the Newton Optimizer]==] /home/jonas/Projects/rtsn/build-code-Desktop-Release/unit_tests [==[Test the Newton Optimizer]==])
set_tests_properties( [==[Test the Newton Optimizer]==] PROPERTIES WORKING_DIRECTORY /home/jonas/Projects/rtsn/build-code-Desktop-Release)
add_test( [==[stopping power computation is equal to ESTAR database]==] /home/jonas/Projects/rtsn/build-code-Desktop-Release/unit_tests [==[stopping power computation is equal to ESTAR database]==])
set_tests_properties( [==[stopping power computation is equal to ESTAR database]==] PROPERTIES WORKING_DIRECTORY /home/jonas/Projects/rtsn/build-code-Desktop-Release)
add_test( [==[checking angular integral of scattering cross sections to be unity]==] /home/jonas/Projects/rtsn/build-code-Desktop-Release/unit_tests [==[checking angular integral of scattering cross sections to be unity]==])
set_tests_properties( [==[checking angular integral of scattering cross sections to be unity]==] PROPERTIES WORKING_DIRECTORY /home/jonas/Projects/rtsn/build-code-Desktop-Release)
add_test( [==[Quadrature Tests]==] /home/jonas/Projects/rtsn/build-code-Desktop-Release/unit_tests [==[Quadrature Tests]==])
set_tests_properties( [==[Quadrature Tests]==] PROPERTIES WORKING_DIRECTORY /home/jonas/Projects/rtsn/build-code-Desktop-Release)
set( unit_tests_TESTS SN_SOLVER PN_SOLVER MN_SOLVER screen_output [==[Read in Config Template]==] [==[test the spherical harmonics basis computation]==] [==[convert image data to grayscale matrix]==] [==[interpolation tests]==] [==[test all scattering kernels]==] [==[unit mesh tests]==] [==[unit numericalflux tests]==] [==[Test the Newton Optimizer]==] [==[stopping power computation is equal to ESTAR database]==] [==[checking angular integral of scattering cross sections to be unity]==] [==[Quadrature Tests]==])
