if(EXISTS "/home/jonas/Projects/rtsn/build-code-Desktop-Release/unit_tests_tests-b858cb2.cmake")
  include("/home/jonas/Projects/rtsn/build-code-Desktop-Release/unit_tests_tests-b858cb2.cmake")
else()
  add_test(unit_tests_NOT_BUILT-b858cb2 unit_tests_NOT_BUILT-b858cb2)
endif()
