/*
 *      DO NOT EDIT THIS FILE
 *
 *      Copy this file when you create
 *      a new quadrature and search for
 *      the word "dummy" and replace it
 *      with the actual content.
 *
 *
 */

#include "quadratures/qdummy.h"

QDummy::QDummy( Config* settings ) : QuadratureBase( settings ) {
    SetName();
    SetNq();
    SetPointsAndWeights();
    SetConnectivity();
}

void QDummy::SetName() {
    _name = "";
    // @TODO: DUMMYCOMPUTATION
}

void QDummy::SetNq() { _nq = 0; }

void QDummy::SetPointsAndWeights() {
    _points  = VectorVector( GetNq() );
    _weights = Vector( GetNq(), 4.0 * M_PI / GetNq() );
    // @TODO: DUMMYCOMPUTATION
}

void QDummy::SetConnectivity() {    // TODO
    VectorVectorU connectivity;
    _connectivity = connectivity;
}
