image: ubuntu:18.04

stages:
  - build
  - test

build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y g++ cmake libopenmpi-dev libblas-dev liblapack-dev git ninja-build
    - git submodule update --init --recursive
    - cd code/build/debug
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=True -DCMAKE_EXPORT_COMPILE_COMMANDS=True ../../
    - ninja

test:
  stage: test
  script:
    - bin/unit_tests
