/*
 *      DO NOT EDIT THIS FILE
 *
 *      Copy this file when you create
 *      a new quadrature and search for
 *      the word "dummy" and replace it
 *      with the actual content.
 *
 *
 */

#ifndef QDUMMY_H
#define QDUMMY_H

#include "quadrature.h"

class QDummy : public Quadrature
{
  public:
    QDummy( unsigned order );
    virtual ~QDummy() {}

    std::string ComputeName();
    unsigned ComputeNq();
    VectorVector ComputePoints();
    Vector ComputeWeights();
    VectorVectorU ComputeConnectivity();
};

#endif    // QDUMMY_H
