/*
 *      DO NOT EDIT THIS FILE
 *
 *      Copy this file when you create
 *      a new quadrature and search for
 *      the word "dummy" and replace it
 *      with the actual content.
 *
 *
 */

#ifndef QDUMMY_H
#define QDUMMY_H

#include "quadraturebase.hpp"

class QDummy : public QuadratureBase
{
  public:
    QDummy( Config* settings );
    QDummy( unsigned quadOrder );
    virtual ~QDummy() {}

    void SetName() override;
    void SetNq() override;
    void SetPointsAndWeights() override;
    void SetConnectivity() override;
};

#endif    // QDUMMY_H
